encrypt:
  key: "Q7udUkHPuA3VnNlOtksSgQ"
spring:
  profiles:
    include: "git"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sudhakaropsmx/dynamicAccount.git"
          username: ""
          password: "8e58b0afa3c53e6bda52bb20c5cdb530c073b23b"
