spring:
  profiles:
    include: git
  cloud:
    config:
      server:
        git:
          uri: DYNAMIC_ACCOUNTS_REPO
          username: GIT_USER
          password: GIT_TOKEN
          basedir: /tmp/config-repo
          refresh-rate: 10
encrypt:
  key: Q7udUkHPuA3VnNlOtksSgQ
